---
- name: play to print ansible_hostname
  hosts: sapprod
  tasks:
   - name: show hostname 
     debug:
      msg: " the name of the server {{inventory_hostname}}  {{inventory_short_name}} "
...       