---
- name: demonstrate file module
  hosts: localhost
  become: true
  tasks:
    - name: create a soft link
      file:
        src: /etc/passwd
        dest: /etc/passwd0
        state: link
        # state: present
        owner: root
        group: ansible
        mode: '0644'

...
this is commit message
new line is added to this file..
