---
- name: Install multiple packages
  hosts: sapprod
  become: yes
  tasks:
   - name: install packages 
     yum:
      name: "{{item}}"
      state: present
     loop:
      - vim
      - git
      - wget
      - curl
...         