---
- name: create a volume group using pv /dev/sdb
  hosts: localhost
  become: true
  tasks:
    - name: create vg
      lvg:
        vg: datavg
        pvs: /dev/sdb
        pesize: 32

    - name: create a volume
      lvol:
        vg: datavg
        lv: datavg01
        size: 512

    - name: create filesystem
      filesystem:
        fstype: xfs
        dev: /dev/datavg/datavg01

    - name: create mount point if it doesn't exist
      file:
        path: /datafs
        state: directory
        mode: '0755'

    - name: mount the filesystem
      mount:
        path: /datafs
        src: /dev/datavg/datavg01
        fstype: xfs
        state: mounted
...
lvg- manages lvm volume groups..
lvol- manages logical volumes..
filesystem- creates a filesystem on a module..
mount- mounts/umount filesystems..
