---
- name: Play to install httpd package
  hosts: sapprod
  become: true
  gather_facts: false

  tasks:
    - name: Task to copy my repo file to remote server
      copy:
        src: /etc/yum.repos.d/rhel95.repo
        dest: /etc/yum.repos.d/rhel95.repo

    - name: Task to install httpd package
      yum:
        name: httpd
        state: latest

    - name: Task to add the port in the firewalld
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true

    - name: Create index.html
      copy:
        dest: /var/www/html/index.html
        content: "<html><h1><center>This is built by Ansible</center></h1></html>"
        mode: '0644'

    - name: Start httpd service
      service:
        name: httpd
        state: started
        enabled: yes

....*******.......







