---
- name: Launch EC2 instance (inline tasks)
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    region: us-east-1
    instance_type: t3.micro
    ami_id: ami-0cae6d6fe6048ca2c
    vpc_subnet_id: subnet-083f3f060e325a588
    security_group: sg-0fbc6f22064b9e8c9
    key_name: jenkins
    instance_name: jenkins-ec2-from-ansible
    count: 1
    assign_public_ip: yes

  tasks:
    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        region: "{{ region }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_id }}"
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        security_group: "{{ security_group }}"
        key_name: "{{ key_name }}"
        wait: yes
        count: "{{ count | int }}"
        network:
          assign_public_ip: "{{ assign_public_ip }}"
        tags:
          Name: "{{ instance_name }}"
      register: ec2_output

    - name: Show EC2 module output
      debug:
        var: ec2_output

