---
- name: pulling vault through jenkins
  hosts: localhost
  gather_facts: false

  vars_files:
    - ansible-vault

  tasks:
    - name: Show password from vault
      debug:
        msg: "Password from vault is {{ password }}"
